run:
  timeout: 5m
  tests: false
  build-tags:
    - integration

issues:
  exclude-dirs:
    - migration
    - performance
    - deployments/monitoring
    - tests
  exclude-files:
    - ".*_test\\.go$"
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - gofmt
    - govet
  disable:
    - typecheck
    - errcheck
    - gosimple
    - unused
    - staticcheck

linters-settings:
  govet:
    enable:
      - assign
      - atomic
      - bools
    disable:
      - shadow
