import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	console.log('🚀 Starting development mode...');
	console.log('📁 Watching for changes in src/ directory');
	console.log('🔄 Plugin will auto-rebuild when files change');
	console.log('💡 In Obsidian: Press Cmd+R or reload plugin to see changes');
	console.log('---');
	
	// 使用正確的 esbuild watch API
	await context.watch();
	
	// 監聽重建事件
	context.onRebuild = (error, result) => {
		if (error) {
			console.error('❌ Build failed:', error);
		} else {
			const now = new Date().toLocaleTimeString();
			console.log(`✅ [${now}] Plugin rebuilt successfully!`);
			console.log('🔄 Reload plugin in Obsidian to see changes');
		}
	};
}